apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: debian-test
spec:
  template:
    spec:
      containers:
      - name: debian-test
        env:
        - name: ENVIRONMENT
          value: e2e
