apiVersion: apps/v1
kind: Rollout
metadata:
  name: debian-test
spec:
  template:
    spec:
      containers:
      - name: debian-test
        env:
        - name: ENVIRONMENT
          value: e2e
strategy:
# --- Everything above this comment are the same as a deployment ---
    canary: # A new field for configurable Canary options
      maxSurge: "10%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 30 #seconds
      - setWeight: 50
      - pause: {}
