
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: staging-ingress
  namespace: argocdtest
  annotations:
          # cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
   
spec:
  rules:
    - host: pocapp1.rel.polysign.io
  backend:
    serviceName: debian-test
    servicePort: 8080
  tls:
    - hosts:
      - pocapp1.rel.polysign.io
      secretName: tls-secret
