
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: debian-test
  namespace: preview
  annotations:
          # cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
   
spec:
  rules:
<<<<<<< HEAD
    - host: pocapp2.rel.polysign.io
=======
    - host: argocdapptest.rel.polysign.io
>>>>>>> c3e43a26ca791a18bfe4daaee52772f72346450e
  backend:
    serviceName: debian-test
    servicePort: 8080
  tls:
    - hosts:
<<<<<<< HEAD
      - pocapp2.rel.polysign.io
=======
      - argocdapptest.rel.polysign.io
>>>>>>> c3e43a26ca791a18bfe4daaee52772f72346450e
      secretName: tls-secret
