apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: debian-test
  name: debian-test
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
  selector:
    k8s-app: debian-test
