apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: application
    app.kubernetes.io/name: debian-test
    app.kubernetes.io/part-of: argocd
  name: debian-test
spec:
  ports:
  - name: debian-test
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: debian-test
